name: dmvtnor-env
channels:
  - conda-forge
  - defaults
dependencies:
  - earthengine-api=0.1.381
  - keras=2.12.0
  - matplotlib=3.8.2
  - notebook=7.0.6
  - numpy=1.23.5
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.11.5
  - scikit-learn=1.3.2
  - scikit-optimize=0.9.0
  - scipy=1.11.4
  - seaborn=0.13.0
  - tensorflow=2.12.0
  - pip:
    - dill==0.3.7
    - fiona==1.9.5
    - geopandas==0.14.1
    - tensorflow-addons==0.23.0
    - -e .
